language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false

stages:
  - 'Tests'
  - name: 'Deploy'
    if: branch = master AND type = push
node_js: '10'

jobs:
  fail_fast: true
  include:
    - stage: 'Tests'
    - stage: 'Deploy'
      script: yarn semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
